// Gemini AI Service for KZ Connect Studio
// Generates event posters with context-aware Kazakhstan city themes
// Provider: Google Gemini (gemini-2.0-flash for text, imagen-4.0-generate-001 for images)

import { GoogleGenerativeAI } from '@google/generative-ai';
import { uploadVideoToCloudinary, downloadVideoWithAuth } from './cloudinary';

export interface EventDetails {
  title: string;
  tagline: string;
  date: string;
  location: string;
  description: string;
  theme: string;
}

export interface RefinedEventDetails extends EventDetails {
  imagePrompt: string;
}

export interface PosterGenerationRequest {
  title: string;
  date: string;
  location: string;
  description?: string;
  theme: PosterTheme;
}

export interface PosterGenerationResult {
  imageUrl: string;
  details: RefinedEventDetails;
  // Kazakhstan AI Law compliance
  isAiGenerated: true;
  aiDisclaimer: string;
  generatedAt: string;
  provider: 'gemini';
}

export type PosterTheme =
  // Стили по категориям событий
  | 'concert-vibe'    // Концерты
  | 'edu-smart'       // Обучение
  | 'business-pro'    // Семинары/Бизнес
  | 'leisure-fun'     // Досуг
  | 'sport-energy'    // Спорт
  | 'kids-magic'      // Для детей
  | 'art-gallery';    // Выставки

// Kazakhstan AI Law - mandatory disclosure
export const AI_DISCLAIMER_KZ = 'Бұл сурет жасанды интеллект арқылы жасалған';
export const AI_DISCLAIMER_RU = 'Изображение сгенерировано искусственным интеллектом';
export const AI_DISCLAIMER_EN = 'This image was generated by artificial intelligence';

export const AI_VIDEO_DISCLAIMER_KZ = 'Бұл бейне жасанды интеллект арқылы жасалған';
export const AI_VIDEO_DISCLAIMER_RU = 'Видео сгенерировано искусственным интеллектом';
export const AI_VIDEO_DISCLAIMER_EN = 'This video was generated by artificial intelligence';

// Video generation types
export interface VideoGenerationRequest {
  title: string;
  date: string;
  location: string;
  description?: string;
  theme: PosterTheme;
  duration?: '4s' | '8s'; // Veo 2 supports 4 and 8 seconds
  aspectRatio?: '16:9' | '9:16'; // Landscape or Portrait
  sourceImage?: string; // Base64 image for image-to-video
}

export interface VideoGenerationResult {
  videoUrl: string;
  thumbnailUrl?: string;
  duration: string;
  aspectRatio: string;
  details: RefinedEventDetails;
  // Kazakhstan AI Law compliance
  isAiGenerated: true;
  aiDisclaimer: string;
  generatedAt: string;
  provider: 'gemini-veo';
}

// Theme descriptions for visual prompts
const THEME_CONFIGS: Record<PosterTheme, { name: string; visualStyle: string; colors: string }> = {
  'concert-vibe': {
    name: 'Concert Vibe',
    visualStyle: 'live music atmosphere, stage lights, crowd silhouettes, microphones, guitars, dynamic performance energy, concert hall ambiance, rock and pop aesthetics',
    colors: 'vibrant purple and pink spotlights, electric blue, warm orange stage glow, dark backgrounds with dramatic lighting',
  },
  'edu-smart': {
    name: 'Edu Smart',
    visualStyle: 'educational environment, books, graduation caps, lightbulbs of ideas, brain illustrations, modern classroom, knowledge symbols, academic excellence',
    colors: 'deep navy blue, forest green, gold accents, clean white backgrounds, scholarly palette',
  },
  'business-pro': {
    name: 'Business Pro',
    visualStyle: 'professional corporate setting, conference room, business charts, handshakes, modern office, networking, keynote presentation, executive style',
    colors: 'sophisticated navy and gray, silver accents, minimal white, professional blue tones',
  },
  'leisure-fun': {
    name: 'Leisure Fun',
    visualStyle: 'relaxed entertainment, friends gathering, cafe atmosphere, movie night, board games, casual fun, weekend vibes, social activities',
    colors: 'warm coral and teal, sunny yellow, playful pastels, inviting warm tones',
  },
  'sport-energy': {
    name: 'Sport Energy',
    visualStyle: 'athletic power, sports equipment, stadium atmosphere, running tracks, gym energy, competition spirit, fitness motivation, dynamic movement',
    colors: 'energetic red and orange, electric green, bold black, high-contrast athletic palette',
  },
  'kids-magic': {
    name: 'Kids Magic',
    visualStyle: 'magical childhood, colorful balloons, cartoon characters, fairy tale elements, playground fun, birthday party vibes, toys and games, wonder and joy',
    colors: 'bright rainbow colors, candy pink, sky blue, cheerful yellow, magical purple sparkles',
  },
  'art-gallery': {
    name: 'Art Gallery',
    visualStyle: 'museum exhibition space, art frames, sculptures, creative installations, gallery lighting, artistic expression, cultural sophistication, curator aesthetic',
    colors: 'elegant white gallery walls, subtle gray, accent colors from famous artworks, sophisticated minimal palette',
  },
};

// City-specific context for better localization
const CITY_CONTEXTS: Record<string, string> = {
  'алматы': 'Almaty mountain backdrop, apple orchards, modern cafes, Medeu, Shymbulak, cosmopolitan vibe',
  'астана': 'Astana futuristic architecture, Baiterek tower, left bank modern buildings, winter capital',
  'жезказган': 'Zhezkazgan industrial heritage, copper mining history, steppe surroundings, local community spirit',
  'караганда': 'Karaganda coal mining heritage, cultural diversity, industrial strength',
  'шымкент': 'Shymkent southern warmth, ancient city, bazaars, traditional hospitality',
  'актау': 'Aktau Caspian Sea coast, modern port city, desert meets ocean, oil industry',
  'атырау': 'Atyrau oil capital, Ural river, business center, energy industry',
  'павлодар': 'Pavlodar industrial city, Irtysh river, northern Kazakhstan',
  'семей': 'Semey historical city, Abay heritage, literary traditions',
  'костанай': 'Kostanay agricultural heartland, wheat fields, northern steppe',
  'актобе': 'Aktobe western gateway, industrial center, multicultural',
  'тараз': 'Taraz ancient city, UNESCO heritage, Silk Road history',
  'усть-каменогорск': 'Ust-Kamenogorsk Altai mountains, zinc industry, natural beauty',
  'кызылорда': 'Kyzylorda rice cultivation, Baikonur proximity, Syr Darya river',
  'туркестан': 'Turkestan spiritual capital, Khoja Ahmed Yasawi mausoleum, pilgrimage site',
};

// Get Gemini client
function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  if (!apiKey) {
    throw new Error('Gemini API key not configured. Set GEMINI_API_KEY environment variable.');
  }
  return new GoogleGenerativeAI(apiKey);
}

// Check if Gemini is available
export function isGeminiAvailable(): boolean {
  const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  return !!apiKey;
}

// Get city context from location string
function getCityContext(location: string): string {
  const locationLower = location.toLowerCase();
  for (const [city, context] of Object.entries(CITY_CONTEXTS)) {
    if (locationLower.includes(city)) {
      return context;
    }
  }
  return 'Kazakhstan local venue, regional character, community event';
}

// Refine event details using Gemini
export async function refineEventDetails(input: PosterGenerationRequest): Promise<RefinedEventDetails> {
  const ai = getGeminiClient();
  const model = ai.getGenerativeModel({ model: 'gemini-2.0-flash' });

  const themeConfig = THEME_CONFIGS[input.theme] || THEME_CONFIGS['concert-vibe'];
  const cityContext = getCityContext(input.location);

  const prompt = `Ты — ведущий креативный директор платформы 'KZ Connect'.
Твоя задача: превратить входящие данные в стильный текст для афиши события в Казахстане.

Входящие данные:
- Название: ${input.title}
- Дата: ${input.date}
- Локация: ${input.location}
- Описание: ${input.description || 'Не указано'}
- Тема: ${themeConfig.name}

Контекст города: ${cityContext}

Инструкции:
1. Создай привлекательный tagline (слоган) для события - короткий, запоминающийся, на русском языке
2. Улучши описание, сделай его кратким но информативным
3. Если локация неточная, предложи конкретное место в этом городе
4. Сгенерируй детальный 'imagePrompt' на АНГЛИЙСКОМ языке для генерации фонового изображения:
   - Визуальный стиль: ${themeConfig.visualStyle}
   - Цветовая гамма: ${themeConfig.colors}
   - Добавь элементы, связанные с городом и контекстом
   - ВАЖНО: Если нужен текст на изображении, используй ТОЛЬКО кириллический шрифт
   - Добавь в промпт: "Cyrillic text only, professional Russian typography, clear readable Cyrillic letters"
   - Формат: вертикальный постер 9:16

Верни ТОЛЬКО JSON без markdown форматирования:
{
  "title": "улучшенное название",
  "tagline": "слоган на русском",
  "date": "форматированная дата",
  "location": "уточнённая локация",
  "description": "краткое описание",
  "theme": "${themeConfig.name}",
  "imagePrompt": "detailed english prompt for image generation"
}`;

  const result = await model.generateContent(prompt);
  const response = result.response;
  const text = response.text();

  // Parse JSON from response (handle potential markdown wrapping)
  let jsonStr = text;
  if (text.includes('```json')) {
    jsonStr = text.replace(/```json\n?/g, '').replace(/```\n?/g, '');
  } else if (text.includes('```')) {
    jsonStr = text.replace(/```\n?/g, '');
  }

  try {
    return JSON.parse(jsonStr.trim());
  } catch (e) {
    // Fallback if parsing fails
    return {
      title: input.title,
      tagline: `${input.title} в ${input.location}`,
      date: input.date,
      location: input.location,
      description: input.description || '',
      theme: themeConfig.name,
      imagePrompt: `Professional event poster background, ${themeConfig.visualStyle}, ${themeConfig.colors}, ${cityContext}, cinematic lighting, 9:16 vertical format. If text present: Cyrillic only, professional Russian typography, clear readable Cyrillic letters`,
    };
  }
}

// Generate poster background image using Gemini/Imagen
export async function generatePosterBackground(prompt: string): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  if (!apiKey) {
    throw new Error('Gemini API key not configured');
  }

  const enhancedPrompt = `Professional high-end cinematic poster background: ${prompt}.
Cinematic lighting, 8k resolution, artistic composition.
CRITICAL: Generate ONLY the background image. DO NOT include ANY text, letters, words, typography, or written content.
The image must be completely text-free - no titles, no captions, no watermarks, no signs with text.
Create a clean visual background suitable for text overlay.
Reflect the unique atmosphere and aesthetics of modern Kazakhstan.
Vertical 9:16 aspect ratio.`;

  // Models to try in order of preference (Imagen 4 - January 2026)
  const imageModels = [
    // Imagen 4 - latest image generation model
    { name: 'imagen-4.0-generate-001', method: 'predict', useResponseModalities: false },
    // Imagen 4 Fast - faster variant
    { name: 'imagen-4.0-fast-generate-001', method: 'predict', useResponseModalities: false },
  ];

  let lastError: string = '';

  for (const modelConfig of imageModels) {
    try {
      if (modelConfig.method === 'generateContent') {
        // Gemini native image generation
        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${modelConfig.name}:generateContent?key=${apiKey}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [{
                parts: [{ text: `Generate a professional event poster image: ${enhancedPrompt}` }]
              }],
              generationConfig: modelConfig.useResponseModalities
                ? { responseModalities: ['IMAGE', 'TEXT'] }
                : {},
            }),
          }
        );

        if (response.ok) {
          const data = await response.json();
          const parts = data.candidates?.[0]?.content?.parts || [];
          for (const part of parts) {
            if (part.inlineData?.data) {
              const mimeType = part.inlineData.mimeType || 'image/png';
              return `data:${mimeType};base64,${part.inlineData.data}`;
            }
          }
        } else {
          const errorData = await response.json().catch(() => ({}));
          lastError = errorData.error?.message || `Model ${modelConfig.name} returned ${response.status}`;
        }
      } else if (modelConfig.method === 'predict') {
        // Imagen API
        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${modelConfig.name}:predict?key=${apiKey}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              instances: [{ prompt: enhancedPrompt }],
              parameters: {
                sampleCount: 1,
                aspectRatio: '9:16',
                safetyFilterLevel: 'block_few',
              },
            }),
          }
        );

        if (response.ok) {
          const data = await response.json();
          if (data.predictions?.[0]?.bytesBase64Encoded) {
            return `data:image/png;base64,${data.predictions[0].bytesBase64Encoded}`;
          }
        } else {
          const errorData = await response.json().catch(() => ({}));
          lastError = errorData.error?.message || `Model ${modelConfig.name} returned ${response.status}`;
        }
      }
    } catch (e) {
      lastError = e instanceof Error ? e.message : 'Unknown error';
      continue;
    }
  }

  // All models failed
  throw new Error(
    `Не удалось сгенерировать изображение. ${lastError}. ` +
    'Попробуйте загрузить своё изображение или повторите попытку позже.'
  );
}

// Full poster generation pipeline
export async function generatePoster(request: PosterGenerationRequest): Promise<PosterGenerationResult> {
  // Step 1: Refine event details with AI
  const refinedDetails = await refineEventDetails(request);

  // Step 2: Generate background image
  const imageUrl = await generatePosterBackground(refinedDetails.imagePrompt);

  return {
    imageUrl,
    details: refinedDetails,
    isAiGenerated: true,
    aiDisclaimer: AI_DISCLAIMER_RU,
    generatedAt: new Date().toISOString(),
    provider: 'gemini',
  };
}

// Get available themes (event category styles)
export function getAvailableThemes(): Array<{
  id: PosterTheme;
  name: string;
  description: string;
  forEventCategory?: string;
}> {
  return [
    { id: 'concert-vibe', name: 'Concert Vibe', description: 'Концерты — живая музыка и энергия', forEventCategory: 'concerts' },
    { id: 'edu-smart', name: 'Edu Smart', description: 'Обучение — знания и развитие', forEventCategory: 'education' },
    { id: 'business-pro', name: 'Business Pro', description: 'Семинары — профессионализм и нетворкинг', forEventCategory: 'seminars' },
    { id: 'leisure-fun', name: 'Leisure Fun', description: 'Досуг — отдых и развлечения', forEventCategory: 'leisure' },
    { id: 'sport-energy', name: 'Sport Energy', description: 'Спорт — движение и победы', forEventCategory: 'sports' },
    { id: 'kids-magic', name: 'Kids Magic', description: 'Для детей — волшебство и радость', forEventCategory: 'children' },
    { id: 'art-gallery', name: 'Art Gallery', description: 'Выставки — искусство и культура', forEventCategory: 'exhibitions' },
  ];
}

// Map event category to recommended theme
export function getRecommendedTheme(eventCategory?: string): PosterTheme {
  const categoryMap: Record<string, PosterTheme> = {
    'concerts': 'concert-vibe',
    'education': 'edu-smart',
    'seminars': 'business-pro',
    'leisure': 'leisure-fun',
    'sports': 'sport-energy',
    'children': 'kids-magic',
    'exhibitions': 'art-gallery',
    'other': 'leisure-fun',
  };
  return categoryMap[eventCategory || ''] || 'concert-vibe';
}

// ============================================
// Video Generation with Veo 2
// ============================================

// Video-specific motion styles for each theme
const VIDEO_THEME_MOTION: Record<PosterTheme, string> = {
  'concert-vibe': 'dynamic stage lighting sweeps, crowd energy waves, guitar strings vibrating, smoke effects rising, spotlight movements',
  'edu-smart': 'pages turning smoothly, lightbulb illuminating, knowledge symbols floating, smooth zoom on learning elements',
  'business-pro': 'professional steadicam through conference, charts animating, handshake motion, elegant corporate pan',
  'leisure-fun': 'playful camera movement, friends laughing animation, cozy cafe atmosphere, warm light transitions',
  'sport-energy': 'fast-paced action shots, athlete motion blur, stadium crowd wave, victory celebration dynamics',
  'kids-magic': 'magical sparkles floating, balloons rising, cartoon elements bouncing, rainbow color transitions, fairy dust effects',
  'art-gallery': 'slow elegant gallery walk, artwork reveal transitions, sculpture rotation, sophisticated lighting changes',
};

/**
 * Generate video prompt from event details
 */
function generateVideoPrompt(details: RefinedEventDetails, aspectRatio: string): string {
  const theme = details.theme.toLowerCase().replace(' ', '-') as PosterTheme;
  const themeConfig = THEME_CONFIGS[theme] || THEME_CONFIGS['concert-vibe'];
  const motionStyle = VIDEO_THEME_MOTION[theme] || VIDEO_THEME_MOTION['concert-vibe'];

  return `Cinematic promotional video for "${details.title}" event.
${details.imagePrompt}.
Motion style: ${motionStyle}.
Color palette: ${themeConfig.colors}.
${aspectRatio === '9:16' ? 'Vertical mobile format, designed for social media stories.' : 'Widescreen cinematic format.'}
Smooth camera movement, professional quality, atmospheric lighting.
CRITICAL TEXT REQUIREMENTS: If any text appears in the video, it MUST be in Cyrillic (Russian) only.
Use professional Russian typography with clear readable Cyrillic letters (А-Я, а-я).
NO Latin letters or mixed alphabets. High-quality Cyrillic text rendering.
Reflecting the unique culture and aesthetics of modern Kazakhstan.`;
}

/**
 * Generate promotional video using Google Veo 2
 * Requires Gemini API key with Veo access
 */
export async function generatePromotionalVideo(request: VideoGenerationRequest): Promise<VideoGenerationResult> {
  const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  if (!apiKey) {
    throw new Error('Gemini API key not configured');
  }

  // Step 1: Refine event details for video
  const refinedDetails = await refineEventDetails(request);

  // Step 2: Generate video prompt
  const aspectRatio = request.aspectRatio || '16:9';
  const duration = request.duration || '8s';
  const videoPrompt = generateVideoPrompt(refinedDetails, aspectRatio);

  // Step 3: Call Veo 3.1 API (January 2026)
  const veoEndpoint = 'https://generativelanguage.googleapis.com/v1beta/models/veo-3.1-generate-preview:predictLongRunning';

  // Parse duration to number (e.g., '8s' -> 8)
  const durationNumber = parseInt(duration.replace('s', ''));

  const requestBody: {
    instances: Array<{ prompt: string; image?: { inlineData: { mimeType: string; data: string } } }>;
    parameters: Record<string, unknown>;
  } = {
    instances: [{
      prompt: videoPrompt,
    }],
    parameters: {
      aspectRatio: aspectRatio,
      durationSeconds: durationNumber,
    },
  };

  // If source image provided (image-to-video)
  if (request.sourceImage) {
    requestBody.instances[0].image = {
      inlineData: {
        mimeType: 'image/png',
        data: request.sourceImage.replace(/^data:image\/\w+;base64,/, ''),
      },
    };
  }

  try {
    const response = await fetch(`${veoEndpoint}?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error?.message || `Veo API error: ${response.status}`);
    }

    const result = await response.json();

    // Veo returns an operation that needs polling
    if (result.name) {
      // Long-running operation - poll for completion
      const videoData = await pollVideoGeneration(result.name, apiKey);
      return {
        videoUrl: videoData.videoUrl,
        thumbnailUrl: videoData.thumbnailUrl,
        duration,
        aspectRatio,
        details: refinedDetails,
        isAiGenerated: true,
        aiDisclaimer: AI_VIDEO_DISCLAIMER_RU,
        generatedAt: new Date().toISOString(),
        provider: 'gemini-veo',
      };
    }

    // Direct response (if available)
    if (result.generatedVideos?.[0]?.video) {
      const videoBase64 = result.generatedVideos[0].video.bytesBase64Encoded;
      return {
        videoUrl: `data:video/mp4;base64,${videoBase64}`,
        duration,
        aspectRatio,
        details: refinedDetails,
        isAiGenerated: true,
        aiDisclaimer: AI_VIDEO_DISCLAIMER_RU,
        generatedAt: new Date().toISOString(),
        provider: 'gemini-veo',
      };
    }

    throw new Error('Unexpected response format from Veo API');
  } catch (error) {
    // Fallback error message
    const message = error instanceof Error ? error.message : 'Video generation failed';
    throw new Error(`Не удалось сгенерировать видео: ${message}`);
  }
}

/**
 * Helper to process video URL - download from Google and upload to Cloudinary
 */
async function processVideoUrl(
  videoUrl: string,
  thumbnailUrl: string | undefined,
  apiKey: string
): Promise<{ videoUrl: string; thumbnailUrl?: string }> {
  // If it's already a base64 data URL, upload directly to Cloudinary
  if (videoUrl.startsWith('data:')) {
    try {
      const cloudinaryResult = await uploadVideoToCloudinary(videoUrl);
      console.log('Video uploaded to Cloudinary:', cloudinaryResult.url);
      return {
        videoUrl: cloudinaryResult.url,
        thumbnailUrl: thumbnailUrl,
      };
    } catch (uploadError) {
      console.error('Failed to upload video to Cloudinary:', uploadError);
      // Return the base64 URL as fallback
      return { videoUrl, thumbnailUrl };
    }
  }

  // If it's a Google URL, download with auth and upload to Cloudinary
  if (videoUrl.includes('generativelanguage.googleapis.com')) {
    try {
      console.log('Downloading video from Google...');
      const base64Video = await downloadVideoWithAuth(videoUrl, apiKey);
      console.log('Video downloaded, uploading to Cloudinary...');
      const cloudinaryResult = await uploadVideoToCloudinary(base64Video);
      console.log('Video uploaded to Cloudinary:', cloudinaryResult.url);
      return {
        videoUrl: cloudinaryResult.url,
        thumbnailUrl: thumbnailUrl,
      };
    } catch (error) {
      console.error('Failed to process video:', error);
      throw new Error(`Failed to process video: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  // For other URLs, return as-is
  return { videoUrl, thumbnailUrl };
}

/**
 * Poll for video generation completion (Veo uses async operations)
 */
async function pollVideoGeneration(
  operationName: string,
  apiKey: string,
  maxAttempts = 60,
  intervalMs = 5000
): Promise<{ videoUrl: string; thumbnailUrl?: string }> {
  const pollEndpoint = `https://generativelanguage.googleapis.com/v1beta/${operationName}?key=${apiKey}`;

  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const response = await fetch(pollEndpoint);
    const result = await response.json();

    if (result.done) {
      if (result.error) {
        throw new Error(result.error.message || 'Video generation failed');
      }

      const response = result.response || {};
      let rawVideoUrl: string | undefined;
      let rawThumbnailUrl: string | undefined;

      // Try multiple response formats (Veo 3.1 may use different structures)
      // Format 1: result.response.generatedVideos[0].video
      if (response.generatedVideos?.[0]) {
        const video = response.generatedVideos[0];
        rawVideoUrl = video.video?.uri || (video.video?.bytesBase64Encoded ? `data:video/mp4;base64,${video.video.bytesBase64Encoded}` : undefined);
        rawThumbnailUrl = video.thumbnail?.uri;
      }

      // Format 2: result.response.videos[0]
      if (!rawVideoUrl && response.videos?.[0]) {
        const video = response.videos[0];
        rawVideoUrl = video.uri || video.url || (video.bytesBase64Encoded ? `data:video/mp4;base64,${video.bytesBase64Encoded}` : undefined) || (video.data ? `data:video/mp4;base64,${video.data}` : undefined);
        rawThumbnailUrl = video.thumbnailUri || video.thumbnail?.uri;
      }

      // Format 3: result.response.predictions[0] (Vertex AI predict format)
      if (!rawVideoUrl && response.predictions?.[0]) {
        const pred = response.predictions[0];
        const videoData = pred.video || pred.bytesBase64Encoded || pred;
        if (typeof videoData === 'string') {
          rawVideoUrl = videoData.startsWith('http') ? videoData : `data:video/mp4;base64,${videoData}`;
        } else if (videoData.uri || videoData.bytesBase64Encoded) {
          rawVideoUrl = videoData.uri || `data:video/mp4;base64,${videoData.bytesBase64Encoded}`;
        }
        rawThumbnailUrl = videoData?.thumbnail?.uri || pred.thumbnail?.uri;
      }

      // Format 4: result.response.generateVideoResponse
      if (!rawVideoUrl && response.generateVideoResponse?.generatedSamples?.[0]) {
        const sample = response.generateVideoResponse.generatedSamples[0];
        rawVideoUrl = sample.video?.uri || (sample.video?.bytesBase64Encoded ? `data:video/mp4;base64,${sample.video.bytesBase64Encoded}` : undefined);
        rawThumbnailUrl = sample.thumbnail?.uri;
      }

      // Format 5: result.result.videos[0] or result.result.generatedVideos[0]
      if (!rawVideoUrl && (result.result?.videos?.[0] || result.result?.generatedVideos?.[0])) {
        const video = result.result.videos?.[0] || result.result.generatedVideos[0];
        rawVideoUrl = video.uri || video.url || video.video?.uri || (video.bytesBase64Encoded ? `data:video/mp4;base64,${video.bytesBase64Encoded}` : undefined) || (video.video?.bytesBase64Encoded ? `data:video/mp4;base64,${video.video.bytesBase64Encoded}` : undefined);
        rawThumbnailUrl = video.thumbnailUri || video.thumbnail?.uri;
      }

      // Format 6: result.metadata with mediaFile
      if (!rawVideoUrl && result.metadata?.mediaFile) {
        rawVideoUrl = result.metadata.mediaFile.uri || result.metadata.mediaFile.url;
        rawThumbnailUrl = result.metadata.thumbnailUri;
      }

      // Format 7: Direct response in result.response
      if (!rawVideoUrl && (response.video || response.uri)) {
        rawVideoUrl = response.video?.uri || response.uri || (response.video?.bytesBase64Encoded ? `data:video/mp4;base64,${response.video.bytesBase64Encoded}` : undefined);
        rawThumbnailUrl = response.thumbnail?.uri;
      }

      if (rawVideoUrl) {
        // Process the video URL - download from Google and upload to Cloudinary
        return await processVideoUrl(rawVideoUrl, rawThumbnailUrl, apiKey);
      }

      // Log the actual response structure for debugging
      const responseKeys = Object.keys(response);
      console.error('Veo API response structure:', JSON.stringify(result, null, 2));
      throw new Error(`No video in completed operation. Response keys: ${responseKeys.length > 0 ? responseKeys.join(', ') : '(empty response)'}`);
    }

    // Wait before next poll
    await new Promise(resolve => setTimeout(resolve, intervalMs));
  }

  throw new Error('Video generation timeout - please try again');
}

/**
 * Check if video generation is available
 */
export function isVideoGenerationAvailable(): boolean {
  const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  // Veo requires special access - check for env flag
  const veoEnabled = process.env.VEO_ENABLED === 'true';
  return !!apiKey && veoEnabled;
}

/**
 * Get video generation capabilities
 */
export function getVideoCapabilities(): {
  available: boolean;
  maxDuration: string;
  aspectRatios: string[];
  features: string[];
} {
  return {
    available: isVideoGenerationAvailable(),
    maxDuration: '8s',
    aspectRatios: ['16:9', '9:16'],
    features: [
      'text-to-video',
      'image-to-video',
      'kazakhstan-themes',
      'city-context',
    ],
  };
}
