// Gemini AI Service for KZ Connect Studio
// Generates event posters with context-aware Kazakhstan city themes
// Provider: Google Gemini (gemini-2.0-flash, imagen-3.0-generate-002)

import { GoogleGenerativeAI } from '@google/generative-ai';

export interface EventDetails {
  title: string;
  tagline: string;
  date: string;
  location: string;
  description: string;
  theme: string;
}

export interface RefinedEventDetails extends EventDetails {
  imagePrompt: string;
}

export interface PosterGenerationRequest {
  title: string;
  date: string;
  location: string;
  description?: string;
  theme: PosterTheme;
}

export interface PosterGenerationResult {
  imageUrl: string;
  details: RefinedEventDetails;
  // Kazakhstan AI Law compliance
  isAiGenerated: true;
  aiDisclaimer: string;
  generatedAt: string;
  provider: 'gemini';
}

export type PosterTheme =
  | 'modern-nomad'    // Этно-футуризм
  | 'urban-pulse'     // Мегаполис
  | 'great-steppe'    // Природа и простор
  | 'cyber-shanyrak'  // Технологии
  | 'silk-road';      // Классика и история

// Kazakhstan AI Law - mandatory disclosure
export const AI_DISCLAIMER_KZ = 'Бұл сурет жасанды интеллект арқылы жасалған';
export const AI_DISCLAIMER_RU = 'Изображение сгенерировано искусственным интеллектом';
export const AI_DISCLAIMER_EN = 'This image was generated by artificial intelligence';

// Theme descriptions for visual prompts
const THEME_CONFIGS: Record<PosterTheme, { name: string; visualStyle: string; colors: string }> = {
  'modern-nomad': {
    name: 'Modern Nomad',
    visualStyle: 'ethno-futurism, traditional Kazakh patterns reimagined in modern minimalist style, subtle shanyrak elements, nomadic heritage meets contemporary design',
    colors: 'gold and deep blue, warm earth tones with modern accents',
  },
  'urban-pulse': {
    name: 'Urban Pulse',
    visualStyle: 'metropolitan cityscape, modern architecture, dynamic urban energy, night city lights, glass and steel',
    colors: 'neon accents on dark backgrounds, electric blue and purple, city lights glow',
  },
  'great-steppe': {
    name: 'Great Steppe',
    visualStyle: 'vast Kazakh steppe landscape, dramatic sky, mountains, natural beauty, open spaces, eagles, horses',
    colors: 'natural greens and browns, golden sunset tones, clear blue sky',
  },
  'cyber-shanyrak': {
    name: 'Cyber Shanyrak',
    visualStyle: 'technological futurism, digital elements, circuit patterns inspired by traditional ornaments, holographic effects, AI and innovation',
    colors: 'cyan and magenta, digital gradients, glowing tech accents',
  },
  'silk-road': {
    name: 'Silk Road',
    visualStyle: 'classical elegance, historical architecture, oriental patterns, ancient trade route heritage, traditional craftsmanship',
    colors: 'rich burgundy and gold, warm amber, antique tones',
  },
};

// City-specific context for better localization
const CITY_CONTEXTS: Record<string, string> = {
  'алматы': 'Almaty mountain backdrop, apple orchards, modern cafes, Medeu, Shymbulak, cosmopolitan vibe',
  'астана': 'Astana futuristic architecture, Baiterek tower, left bank modern buildings, winter capital',
  'жезказган': 'Zhezkazgan industrial heritage, copper mining history, steppe surroundings, local community spirit',
  'караганда': 'Karaganda coal mining heritage, cultural diversity, industrial strength',
  'шымкент': 'Shymkent southern warmth, ancient city, bazaars, traditional hospitality',
  'актау': 'Aktau Caspian Sea coast, modern port city, desert meets ocean, oil industry',
  'атырау': 'Atyrau oil capital, Ural river, business center, energy industry',
  'павлодар': 'Pavlodar industrial city, Irtysh river, northern Kazakhstan',
  'семей': 'Semey historical city, Abay heritage, literary traditions',
  'костанай': 'Kostanay agricultural heartland, wheat fields, northern steppe',
  'актобе': 'Aktobe western gateway, industrial center, multicultural',
  'тараз': 'Taraz ancient city, UNESCO heritage, Silk Road history',
  'усть-каменогорск': 'Ust-Kamenogorsk Altai mountains, zinc industry, natural beauty',
  'кызылорда': 'Kyzylorda rice cultivation, Baikonur proximity, Syr Darya river',
  'туркестан': 'Turkestan spiritual capital, Khoja Ahmed Yasawi mausoleum, pilgrimage site',
};

// Get Gemini client
function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  if (!apiKey) {
    throw new Error('Gemini API key not configured. Set GEMINI_API_KEY environment variable.');
  }
  return new GoogleGenerativeAI(apiKey);
}

// Check if Gemini is available
export function isGeminiAvailable(): boolean {
  const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  return !!apiKey;
}

// Get city context from location string
function getCityContext(location: string): string {
  const locationLower = location.toLowerCase();
  for (const [city, context] of Object.entries(CITY_CONTEXTS)) {
    if (locationLower.includes(city)) {
      return context;
    }
  }
  return 'Kazakhstan local venue, regional character, community event';
}

// Refine event details using Gemini
export async function refineEventDetails(input: PosterGenerationRequest): Promise<RefinedEventDetails> {
  const ai = getGeminiClient();
  const model = ai.getGenerativeModel({ model: 'gemini-2.0-flash' });

  const themeConfig = THEME_CONFIGS[input.theme] || THEME_CONFIGS['modern-nomad'];
  const cityContext = getCityContext(input.location);

  const prompt = `Ты — ведущий креативный директор платформы 'KZ Connect'.
Твоя задача: превратить входящие данные в стильный текст для афиши события в Казахстане.

Входящие данные:
- Название: ${input.title}
- Дата: ${input.date}
- Локация: ${input.location}
- Описание: ${input.description || 'Не указано'}
- Тема: ${themeConfig.name}

Контекст города: ${cityContext}

Инструкции:
1. Создай привлекательный tagline (слоган) для события - короткий, запоминающийся, на русском языке
2. Улучши описание, сделай его кратким но информативным
3. Если локация неточная, предложи конкретное место в этом городе
4. Сгенерируй детальный 'imagePrompt' на АНГЛИЙСКОМ языке для генерации фонового изображения:
   - Визуальный стиль: ${themeConfig.visualStyle}
   - Цветовая гамма: ${themeConfig.colors}
   - Добавь элементы, связанные с городом и контекстом
   - Избегай текста на изображении
   - Формат: вертикальный постер 9:16

Верни ТОЛЬКО JSON без markdown форматирования:
{
  "title": "улучшенное название",
  "tagline": "слоган на русском",
  "date": "форматированная дата",
  "location": "уточнённая локация",
  "description": "краткое описание",
  "theme": "${themeConfig.name}",
  "imagePrompt": "detailed english prompt for image generation"
}`;

  const result = await model.generateContent(prompt);
  const response = result.response;
  const text = response.text();

  // Parse JSON from response (handle potential markdown wrapping)
  let jsonStr = text;
  if (text.includes('```json')) {
    jsonStr = text.replace(/```json\n?/g, '').replace(/```\n?/g, '');
  } else if (text.includes('```')) {
    jsonStr = text.replace(/```\n?/g, '');
  }

  try {
    return JSON.parse(jsonStr.trim());
  } catch (e) {
    // Fallback if parsing fails
    return {
      title: input.title,
      tagline: `${input.title} в ${input.location}`,
      date: input.date,
      location: input.location,
      description: input.description || '',
      theme: themeConfig.name,
      imagePrompt: `Professional event poster background, ${themeConfig.visualStyle}, ${themeConfig.colors}, ${cityContext}, cinematic lighting, 9:16 vertical format, no text`,
    };
  }
}

// Generate poster background image using Gemini Imagen
export async function generatePosterBackground(prompt: string): Promise<string> {
  const ai = getGeminiClient();

  // Use Imagen 3 for image generation
  const model = ai.getGenerativeModel({ model: 'imagen-3.0-generate-002' });

  const enhancedPrompt = `Professional high-end cinematic poster background: ${prompt}. Cinematic lighting, 8k resolution, artistic composition, no text, no letters, no words. Reflect the unique atmosphere and aesthetics of modern Kazakhstan. Vertical 9:16 aspect ratio.`;

  try {
    const result = await model.generateContent({
      contents: [{ role: 'user', parts: [{ text: enhancedPrompt }] }],
      generationConfig: {
        responseMimeType: 'image/png',
      },
    });

    const response = result.response;

    // Check for inline image data
    if (response.candidates && response.candidates[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if ('inlineData' in part && part.inlineData?.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error('No image data in response');
  } catch (error) {
    // Fallback to gemini-2.0-flash-exp for image generation
    const fallbackModel = ai.getGenerativeModel({ model: 'gemini-2.0-flash-exp' });

    const result = await fallbackModel.generateContent({
      contents: [{
        role: 'user',
        parts: [{ text: `Generate an image: ${enhancedPrompt}` }]
      }],
    });

    const response = result.response;

    if (response.candidates && response.candidates[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if ('inlineData' in part && part.inlineData?.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error('Не удалось сгенерировать изображение. Попробуйте другой промпт.');
  }
}

// Full poster generation pipeline
export async function generatePoster(request: PosterGenerationRequest): Promise<PosterGenerationResult> {
  // Step 1: Refine event details with AI
  const refinedDetails = await refineEventDetails(request);

  // Step 2: Generate background image
  const imageUrl = await generatePosterBackground(refinedDetails.imagePrompt);

  return {
    imageUrl,
    details: refinedDetails,
    isAiGenerated: true,
    aiDisclaimer: AI_DISCLAIMER_RU,
    generatedAt: new Date().toISOString(),
    provider: 'gemini',
  };
}

// Get available themes
export function getAvailableThemes(): Array<{ id: PosterTheme; name: string; description: string }> {
  return [
    { id: 'modern-nomad', name: 'Modern Nomad', description: 'Этно-футуризм — традиции в современном прочтении' },
    { id: 'urban-pulse', name: 'Urban Pulse', description: 'Мегаполис — энергия большого города' },
    { id: 'great-steppe', name: 'Great Steppe', description: 'Великая степь — природа и простор' },
    { id: 'cyber-shanyrak', name: 'Cyber Shanyrak', description: 'Технологии — цифровое будущее' },
    { id: 'silk-road', name: 'Silk Road', description: 'Шёлковый путь — классика и история' },
  ];
}
