// AI Image Generation Service
// Business Premium feature for generating promotional images
// Provider: Ideogram V2

export type AiProvider = 'ideogram';

export interface NanoBananaConfig {
  provider: AiProvider;
  apiKey: string;
  apiUrl: string;
  model: string;
}

export interface GenerationRequest {
  prompt: string;
  style?: 'banner' | 'promo' | 'event' | 'poster' | 'social';
  width?: number;
  height?: number;
}

export interface GenerationResult {
  imageUrl: string;
  revisedPrompt?: string;
  generationId: string;
  // Kazakhstan AI Law compliance - mandatory marking
  isAiGenerated: true;
  aiDisclaimer: string;
  generatedAt: string;
  provider: AiProvider;
}

// Kazakhstan AI Law - mandatory disclosure text
export const AI_DISCLAIMER_KZ = 'Бұл сурет жасанды интеллект арқылы жасалған';
export const AI_DISCLAIMER_RU = 'Изображение сгенерировано искусственным интеллектом';
export const AI_DISCLAIMER_EN = 'This image was generated by artificial intelligence';

// Style presets with optimized prompts for each use case
const STYLE_PRESETS: Record<string, { suffix: string; width: number; height: number }> = {
  banner: {
    suffix: ', professional banner design, high quality, modern, clean layout, marketing material',
    width: 1200,
    height: 400,
  },
  promo: {
    suffix: ', promotional poster, vibrant colors, eye-catching, commercial design, sale advertisement',
    width: 1200,
    height: 675,
  },
  event: {
    suffix: ', event poster design, festive, celebration, entertainment, announcement style',
    width: 1200,
    height: 675,
  },
  poster: {
    suffix: ', artistic poster, bold typography space, graphic design, professional print quality',
    width: 800,
    height: 1200,
  },
  social: {
    suffix: ', social media post, engaging, shareable, modern aesthetic, instagram style',
    width: 1080,
    height: 1080,
  },
};

// Ideogram configuration
const IDEOGRAM_CONFIG = {
  url: 'https://api.ideogram.ai/generate',
  model: 'V_2',
};

// Get config from environment
export function getNanoBananaConfig(): NanoBananaConfig {
  const apiKey = process.env.IDEOGRAM_API_KEY || '';
  const apiUrl = process.env.NANOBANANA_API_URL || IDEOGRAM_CONFIG.url;
  const model = process.env.AI_IMAGE_MODEL || IDEOGRAM_CONFIG.model;

  return { provider: 'ideogram', apiKey, apiUrl, model };
}

// Check if AI generation is available
export function isAiGenerationAvailable(): boolean {
  const config = getNanoBananaConfig();
  return !!config.apiKey;
}

// Get current provider info
export function getProviderInfo(): { provider: AiProvider; model: string; isFree: boolean } {
  const config = getNanoBananaConfig();
  return {
    provider: config.provider,
    model: config.model,
    isFree: false,
  };
}

// Generate image using Ideogram V2
async function generateWithIdeogram(
  config: NanoBananaConfig,
  enhancedPrompt: string,
  width: number,
  height: number
): Promise<GenerationResult> {
  // Determine aspect ratio for Ideogram
  let aspectRatio = 'ASPECT_1_1';
  if (width > height * 1.5) {
    aspectRatio = 'ASPECT_16_9';
  } else if (width > height * 1.2) {
    aspectRatio = 'ASPECT_4_3';
  } else if (height > width * 1.5) {
    aspectRatio = 'ASPECT_9_16';
  } else if (height > width * 1.2) {
    aspectRatio = 'ASPECT_3_4';
  }

  const response = await fetch(config.apiUrl, {
    method: 'POST',
    headers: {
      'Api-Key': config.apiKey,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      image_request: {
        prompt: enhancedPrompt,
        aspect_ratio: aspectRatio,
        model: config.model,
        magic_prompt_option: 'AUTO',
      },
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: 'Unknown error' }));
    const errorMessage = error.message || error.error?.message || `Ideogram API request failed: ${response.status}`;
    throw new Error(errorMessage);
  }

  const result = await response.json();

  if (!result.data || !result.data[0]?.url) {
    throw new Error('Invalid response from Ideogram');
  }

  return {
    imageUrl: result.data[0].url,
    revisedPrompt: result.data[0].prompt,
    generationId: `gen_ideogram_${result.data[0].seed || Date.now()}`,
    // Kazakhstan AI Law compliance
    isAiGenerated: true as const,
    aiDisclaimer: AI_DISCLAIMER_RU,
    generatedAt: new Date().toISOString(),
    provider: 'ideogram' as const,
  };
}

// Generate image using AI (main function)
export async function generateImage(request: GenerationRequest): Promise<GenerationResult> {
  const config = getNanoBananaConfig();

  if (!config.apiKey) {
    throw new Error('AI image generation not configured. Set IDEOGRAM_API_KEY environment variable.');
  }

  const stylePreset = request.style ? STYLE_PRESETS[request.style] : null;

  // Build the enhanced prompt
  let enhancedPrompt = translatePromptForAI(request.prompt);
  if (stylePreset) {
    enhancedPrompt += stylePreset.suffix;
  }

  // Add quality boosters for better results
  enhancedPrompt += ', high quality, detailed, professional';

  // Determine dimensions
  const width = request.width || stylePreset?.width || 1024;
  const height = request.height || stylePreset?.height || 1024;

  return await generateWithIdeogram(config, enhancedPrompt, width, height);
}

// Generate prompt suggestions based on content type
export function generatePromptSuggestions(contentType: 'event' | 'promotion' | 'banner', context?: {
  title?: string;
  description?: string;
  category?: string;
  discount?: string;
}): string[] {
  const suggestions: string[] = [];

  if (contentType === 'event') {
    const category = context?.category || 'event';
    suggestions.push(
      `Афиша ${context?.title || 'события'} в Жезказгане, современный дизайн`,
      `Красочный постер для ${category === 'concerts' ? 'концерта' : category === 'sports' ? 'спортивного мероприятия' : 'события'}`,
      `Яркий баннер для анонса мероприятия, казахстанский колорит`,
    );
  } else if (contentType === 'promotion') {
    suggestions.push(
      `Рекламный баннер "Скидка ${context?.discount || '20%'}", привлекательный дизайн`,
      `Промо-постер для акции ${context?.title || ''}, яркие цвета`,
      `Баннер распродажи, современный минималистичный стиль`,
    );
  } else if (contentType === 'banner') {
    suggestions.push(
      `Рекламный баннер для бизнеса в Жезказгане, профессиональный дизайн`,
      `Корпоративный баннер, современный стиль, чистый дизайн`,
      `Привлекательный рекламный материал для городского бизнеса`,
    );
  }

  return suggestions;
}

// Image idea structure
export interface ImageIdea {
  id: number;
  title: string;
  description: string;
  prompt: string;
  style: 'banner' | 'promo' | 'event' | 'poster' | 'social';
  tags: string[];
}

// Category-specific visual themes
const CATEGORY_THEMES: Record<string, { visuals: string[]; colors: string[]; mood: string }> = {
  concerts: {
    visuals: ['microphone', 'stage lights', 'musical notes', 'crowd silhouettes', 'guitar'],
    colors: ['neon purple', 'electric blue', 'vibrant pink'],
    mood: 'energetic, dynamic, exciting',
  },
  education: {
    visuals: ['books', 'graduation cap', 'lightbulb', 'notebook', 'classroom'],
    colors: ['deep blue', 'gold', 'white'],
    mood: 'inspiring, professional, knowledge',
  },
  seminars: {
    visuals: ['presentation screen', 'conference room', 'microphone', 'audience'],
    colors: ['corporate blue', 'gray', 'white'],
    mood: 'professional, business, informative',
  },
  leisure: {
    visuals: ['park', 'friends gathering', 'outdoor activities', 'sunset'],
    colors: ['warm orange', 'green', 'sky blue'],
    mood: 'relaxing, fun, friendly',
  },
  sports: {
    visuals: ['stadium', 'athletes', 'trophy', 'sports equipment', 'action shots'],
    colors: ['energetic red', 'green field', 'white'],
    mood: 'powerful, competitive, active',
  },
  children: {
    visuals: ['balloons', 'toys', 'cartoon characters', 'playground', 'bright colors'],
    colors: ['bright yellow', 'sky blue', 'pink', 'green'],
    mood: 'playful, joyful, colorful',
  },
  exhibitions: {
    visuals: ['art gallery', 'paintings', 'sculptures', 'museum interior'],
    colors: ['elegant white', 'gold accents', 'neutral tones'],
    mood: 'artistic, elegant, cultural',
  },
  other: {
    visuals: ['abstract shapes', 'modern design', 'city elements'],
    colors: ['modern blue', 'orange accent', 'gray'],
    mood: 'versatile, modern, appealing',
  },
};

// Generate 3 image ideas based on event information
export function generateImageIdeas(context: {
  title?: string;
  description?: string;
  category?: string;
  date?: string;
  location?: string;
}): ImageIdea[] {
  const category = context.category || 'other';
  const theme = CATEGORY_THEMES[category] || CATEGORY_THEMES.other;
  const title = context.title || 'Мероприятие';

  const ideas: ImageIdea[] = [
    {
      id: 1,
      title: 'Современный минималистичный постер',
      description: `Чистый дизайн с акцентом на типографику и ${theme.visuals[0]}. Использует ${theme.colors[0]} как основной цвет.`,
      prompt: `Modern minimalist event poster for "${title}", clean typography, ${theme.visuals[0]}, ${theme.colors[0]} color scheme, ${theme.mood}, professional design, Kazakhstan style, high quality`,
      style: 'poster',
      tags: ['минимализм', 'современный', 'типографика'],
    },
    {
      id: 2,
      title: 'Яркий иллюстрированный баннер',
      description: `Динамичная композиция с элементами ${theme.visuals.slice(0, 2).join(' и ')}. Яркие цвета создают привлекательный визуал.`,
      prompt: `Vibrant illustrated banner for "${title}", featuring ${theme.visuals.slice(0, 3).join(', ')}, ${theme.colors.join(' and ')} colors, ${theme.mood} atmosphere, eye-catching design, Central Asian motifs, digital art style`,
      style: 'banner',
      tags: ['яркий', 'иллюстрация', 'баннер'],
    },
    {
      id: 3,
      title: 'Фотореалистичный промо-материал',
      description: `Реалистичное изображение с атмосферой ${category === 'concerts' ? 'концерта' : category === 'sports' ? 'спортивного события' : 'мероприятия'}.`,
      prompt: `Photorealistic promotional image for "${title}" event, ${theme.visuals[Math.floor(Math.random() * theme.visuals.length)]}, dramatic lighting, ${theme.mood}, cinematic composition, ${theme.colors[0]} tones, professional photography style, Kazakhstan`,
      style: 'event',
      tags: ['реалистичный', 'промо', 'атмосферный'],
    },
  ];

  if (context.location) {
    ideas.forEach(idea => {
      idea.prompt += `, ${context.location} venue`;
    });
  }

  return ideas;
}

// Translate common Kazakh/Russian business terms to English for better AI results
export function translatePromptForAI(prompt: string): string {
  const translations: Record<string, string> = {
    'скидка': 'discount sale',
    'акция': 'special offer promotion',
    'распродажа': 'big sale clearance',
    'концерт': 'concert music event',
    'ресторан': 'restaurant dining',
    'кафе': 'cafe coffee shop',
    'спорт': 'sports fitness',
    'красота': 'beauty salon spa',
    'жезказган': 'Zhezkazgan Kazakhstan city',
    'мероприятие': 'event celebration',
    'праздник': 'holiday festival celebration',
    'открытие': 'grand opening',
    'новинка': 'new arrival product',
    'меню': 'food menu restaurant',
    'доставка': 'delivery service',
    'фитнес': 'fitness gym workout',
    'салон': 'salon service',
    'магазин': 'shop store retail',
  };

  let translated = prompt.toLowerCase();
  for (const [ru, en] of Object.entries(translations)) {
    translated = translated.replace(new RegExp(ru, 'gi'), en);
  }

  return translated;
}
